use CompraVenta

ALTER TABLE TM_PRODUCTO
ALTER COLUMN PROD_STOCK numeric(18,2) NOT NULL;

EXEC sp_helptext 'SP_I_VENTA_01';

CREATE PROCEDURE SP_I_VENTA_01    
@VENT_ID INT,    
@PROD_ID INT,    
@PROD_PVENTA NUMERIC(18,2),    
@DETV_CANT NUMERIC(18,2)    
AS    
BEGIN    
 INSERT TD_VENTA_DETALLE    
 (VENT_ID,PROD_ID,PROD_PVENTA,DETV_CANT,DETV_TOTAL,FECH_CREA,EST)    
 VALUES    
 (@VENT_ID,@PROD_ID,@PROD_PVENTA,@DETV_CANT,@PROD_PVENTA * @DETV_CANT,GETDATE(),1)    
END

-- Lista todos los SP que contienen 'STOCK' en su nombre o código
SELECT name
FROM sys.procedures
WHERE OBJECT_DEFINITION(OBJECT_ID) LIKE '%STOCK%';

EXEC sp_helptext 'SP_I_VENTA_02';

--TODO: Guardar venta    
ALTER PROCEDURE SP_U_VENTA_03    
@VENT_ID INT,      
@PAG_ID INT,      
@CLI_ID INT,      
@CLI_RUC VARCHAR(20),      
@CLI_DIRECC VARCHAR(150),      
@CLI_CORREO VARCHAR(150),      
@VENT_COMENT VARCHAR(250),      
@MON_ID INT,  
@DOC_ID INT  
AS      
BEGIN      
 UPDATE TM_VENTA      
 SET      
  PAG_ID = @PAG_ID,      
  CLI_ID = @CLI_ID,      
  CLI_RUC = @CLI_RUC,      
  CLI_DIRECC = @CLI_DIRECC,      
  CLI_CORREO = @CLI_CORREO,      
  VENT_COMENT = @VENT_COMENT,      
  MON_ID = @MON_ID,  
  DOC_ID = @DOC_ID,  
  FECH_CREA = GETDATE(),      
  EST = 1      
 WHERE      
  VENT_ID = @VENT_ID      
       
 DECLARE @ID_REGISTRO INT      
 DECLARE @PROD_ID INT      
 DECLARE @CANT NUMERIC(18,2)      
      
 DECLARE CUR CURSOR FOR SELECT DETV_ID FROM TD_VENTA_DETALLE WHERE VENT_ID=@VENT_ID      
 OPEN CUR      
 FETCH NEXT FROM CUR INTO @ID_REGISTRO      
 WHILE @@FETCH_STATUS=0      
  BEGIN      
   SELECT @PROD_ID=PROD_ID FROM TD_VENTA_DETALLE WHERE DETV_ID = @ID_REGISTRO      
         
   SELECT @CANT=DETV_CANT FROM TD_VENTA_DETALLE WHERE DETV_ID = @ID_REGISTRO      
      
   UPDATE TM_PRODUCTO      
   SET      
    PROD_STOCK = PROD_STOCK - @CANT      
   WHERE      
    PROD_ID = @PROD_ID      
      
   FETCH NEXT FROM CUR INTO @ID_REGISTRO      
  END      
 CLOSE CUR      
 DEALLOCATE CUR      
END  

TRUNCATE TABLE TD_VENTA_DETALLE;


--ACTUALIZAR REGISTRO  
ALTER PROCEDURE SP_U_PRODUCTO_01  
@PROD_ID INT,  
@SUC_ID INT,  
@CAT_ID INT,  
@PROD_NOM VARCHAR(150),  
@PROD_DESCRIP VARCHAR(150),  
@UND_ID INT,  
@MON_ID INT,  
@PROD_PCOMPRA NUMERIC(18,2),  
@PROD_PVENTA NUMERIC(18,2),  
@PROD_STOCK NUMERIC(18,2),  
@PROD_FECHAVEN DATE,  
@PROD_IMG VARCHAR(MAX)  
AS  
BEGIN  
 UPDATE TM_PRODUCTO  
 SET  
  SUC_ID = @SUC_ID,  
  CAT_ID = @CAT_ID,  
  PROD_NOM = @PROD_NOM,  
  PROD_DESCRIP = @PROD_DESCRIP,  
  UND_ID = @UND_ID,  
  MON_ID = @MON_ID,  
  PROD_PCOMPRA = @PROD_PCOMPRA,  
  PROD_PVENTA = @PROD_PVENTA,  
  PROD_STOCK = @PROD_STOCK,  
  PROD_FECHAVEN = @PROD_FECHAVEN,  
  PROD_IMG = @PROD_IMG  
 WHERE  
  PROD_ID = @PROD_ID  
END

SELECT name
FROM sys.procedures
WHERE OBJECT_DEFINITION(OBJECT_ID) LIKE '%VENT%';


ALTER VIEW VW_BALANCE AS
SELECT 
    p.PROD_ID,
    p.PROD_NOM AS Producto,
    p.PROD_PCOMPRA AS PrecioCompra,
    p.PROD_STOCK AS Stock,
    p.PROD_PVENTA AS PrecioVenta,

    -- Proyecciones con el stock actual
    (p.PROD_STOCK * p.PROD_PVENTA) AS TotalEsperado,
    (p.PROD_STOCK * p.PROD_PCOMPRA) AS TotalInvertido,
    ((p.PROD_STOCK * p.PROD_PVENTA) - (p.PROD_STOCK * p.PROD_PCOMPRA)) AS TotalGanancias,

    -- Totales reales de lo vendido
    ISNULL(SUM(d.DETV_TOTAL),0) AS VentaRealizada,
    ISNULL(SUM(d.DETV_TOTAL),0) - ISNULL(SUM(d.DETV_CANT * p.PROD_PCOMPRA),0) AS GananciaRealizada

FROM 
    TM_PRODUCTO p
LEFT JOIN 
    TD_VENTA_DETALLE d ON p.PROD_ID = d.PROD_ID AND d.EST = 1
WHERE 
    p.EST = 1
GROUP BY 
    p.PROD_ID, p.PROD_NOM, p.PROD_PCOMPRA, p.PROD_STOCK, p.PROD_PVENTA;




    SELECT * FROM VW_BALANCE;
