--TODO: Guardar venta  
ALTER PROCEDURE SP_U_VENTA_03  
@VENT_ID INT,    
@PAG_ID INT,    
@CLI_ID INT,    
@CLI_RUC VARCHAR(20),    
@CLI_DIRECC VARCHAR(150),    
@CLI_CORREO VARCHAR(150),    
@VENT_COMENT VARCHAR(250),    
@MON_ID INT,
@DOC_ID INT
AS    
BEGIN    
 UPDATE TM_VENTA    
 SET    
  PAG_ID = @PAG_ID,    
  CLI_ID = @CLI_ID,    
  CLI_RUC = @CLI_RUC,    
  CLI_DIRECC = @CLI_DIRECC,    
  CLI_CORREO = @CLI_CORREO,    
  VENT_COMENT = @VENT_COMENT,    
  MON_ID = @MON_ID,
  DOC_ID = @DOC_ID,
  FECH_CREA = GETDATE(),    
  EST = 1    
 WHERE    
  VENT_ID = @VENT_ID    
     
 DECLARE @ID_REGISTRO INT    
 DECLARE @PROD_ID INT    
 DECLARE @CANT INT    
    
 DECLARE CUR CURSOR FOR SELECT DETV_ID FROM TD_VENTA_DETALLE WHERE VENT_ID=@VENT_ID    
 OPEN CUR    
 FETCH NEXT FROM CUR INTO @ID_REGISTRO    
 WHILE @@FETCH_STATUS=0    
  BEGIN    
   SELECT @PROD_ID=PROD_ID FROM TD_VENTA_DETALLE WHERE DETV_ID = @ID_REGISTRO    
       
   SELECT @CANT=DETV_CANT FROM TD_VENTA_DETALLE WHERE DETV_ID = @ID_REGISTRO    
    
   UPDATE TM_PRODUCTO    
   SET    
    PROD_STOCK = PROD_STOCK - @CANT    
   WHERE    
    PROD_ID = @PROD_ID    
    
   FETCH NEXT FROM CUR INTO @ID_REGISTRO    
  END    
 CLOSE CUR    
 DEALLOCATE CUR    
END


ALTER PROCEDURE SP_U_VENTA_01  
@VENT_ID INT  
AS  
BEGIN  
SET NOCOUNT ON  
 UPDATE TM_VENTA  
 SET  
  VENT_SUBTOTAL = (SELECT SUM(DETV_TOTAL) AS VENT_SUBTOTAL FROM TD_VENTA_DETALLE WHERE VENT_ID=@VENT_ID AND EST=1),  
  VENT_IGV = (SELECT SUM(DETV_TOTAL) AS VENT_SUBTOTAL FROM TD_VENTA_DETALLE WHERE VENT_ID=@VENT_ID AND EST=1) * 0.0,  
  VENT_TOTAL = (SELECT SUM(DETV_TOTAL) AS VENT_SUBTOTAL FROM TD_VENTA_DETALLE WHERE VENT_ID=@VENT_ID AND EST=1) + ((SELECT SUM(DETV_TOTAL) AS VENT_SUBTOTAL FROM TD_VENTA_DETALLE WHERE VENT_ID=@VENT_ID AND EST=1) * 0.0)  
 WHERE  
  VENT_ID = @VENT_ID  
  
 SELECT   
  VENT_SUBTOTAL,  
  VENT_IGV,  
  VENT_TOTAL   
 FROM   
  TM_VENTA  
 WHERE  
  VENT_ID = @VENT_ID  
SET NOCOUNT OFF  
END


ALTER PROCEDURE SP_L_COMPRAS_04 
@SUC_ID INT
AS
BEGIN

SELECT TOP (5) 
TD_COMPRA_DETALLE.PROD_ID, 
SUM(TD_COMPRA_DETALLE.DETC_CANT) AS CANT, 
TM_PRODUCTO.PROD_NOM, 
TM_PRODUCTO.PROD_PCOMPRA,
TM_CATEGORIA.CAT_NOM, 
TM_UNIDAD.UND_NOM, 
TM_PRODUCTO.PROD_STOCK, 
TM_PRODUCTO.PROD_IMG,
TM_MONEDA.MON_NOM,
SUM(TM_COMPRA.COMPR_TOTAL) AS TOTAL
FROM     
TD_COMPRA_DETALLE INNER JOIN
TM_PRODUCTO ON TD_COMPRA_DETALLE.PROD_ID = TM_PRODUCTO.PROD_ID INNER JOIN
TM_CATEGORIA ON TM_PRODUCTO.CAT_ID = TM_CATEGORIA.CAT_ID INNER JOIN
TM_UNIDAD ON TM_PRODUCTO.UND_ID = TM_UNIDAD.UND_ID INNER JOIN
TM_COMPRA ON TD_COMPRA_DETALLE.COMPR_ID = TM_COMPRA.COMPR_ID INNER JOIN
TM_MONEDA ON TM_COMPRA.MON_ID = TM_MONEDA.MON_ID
WHERE
TM_PRODUCTO.EST=1
AND TM_PRODUCTO.EST=1
AND TM_COMPRA.SUC_ID=@SUC_ID
GROUP BY 
TD_COMPRA_DETALLE.PROD_ID, 
TM_PRODUCTO.PROD_NOM, 
TM_PRODUCTO.PROD_PCOMPRA, 
TM_CATEGORIA.CAT_NOM, 
TM_UNIDAD.UND_NOM, 
TM_PRODUCTO.PROD_STOCK, 
TM_PRODUCTO.PROD_IMG,
TM_MONEDA.MON_NOM
ORDER BY CANT DESC
END